### ISSUE TITLE
Is there a way to check the current axis values?

### ISSUE THREAD

**Issue by wbuijsman** [linusg/xbox360controller#14]
I'm trying to use this library and the buttons work great so far! I'm just having some issues with getting the axes to work.

I was trying to get continuous input from the axes (like as long as `axis.x > 0.5`, to move a servo in a certain direction), but it seems that there is only the `axis.when_moved` option which only gives me an axis value when there is a significant change. So when I hold down the L axis in a direction, I only get a few inputs and then nothing, until the value changes again. So if I wiggle the axis a bit it does exactly what I want :)

What I would like to do instead is along the lines of:
```
While True:
    if controller.axis.x > 0.5:
        moveServo()
```

Is there a way to implement this using this library? I feel like I am missing something obvious.

**Comment by linusg** [comment]
> Is there a way to implement this using this library? I feel like I am missing something obvious.

yeah, pretty much just that should work - the following are exposed:

https://github.com/linusg/xbox360controller/blob/f8f9b78cb6b68c3352366b509e10ad3f1871f0e8/xbox360controller/controller.py#L190-L194

So try (haven't tested it):

```python3
from xbox360controller import Xbox360Controller

with Xbox360Controller() as controller:
    while True:
        if controller.axis_l.x > 0.5:
            moveServo()
```

**Comment by wbuijsman** [comment]
Works like a charm! Thanks you for writing this library, it has been a big help for a beginner user of a raspberry Pi such as myself!
