### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by Weeesel** [linusg/xbox360controller#20]
The polling in the event loop seems to be quiet hard on my CPU. `top` calls it `10 %CPU` just for idling, not pressing anything in the [example](https://github.com/linusg/xbox360controller#basics).

#### Suggestion
I find
https://github.com/linusg/xbox360controller/blob/22ec7d3fe68b302f9f451fa5f23dba1075b1b1af/xbox360controller/controller.py#L276
quite a low value, shouldnt `0.01` do it quite nicely in measures of human reaction time?! This brings the CPU load for idling down to `1.3%` on my box. I havent tested this for gaming though... 

Thanks for your project, working well for me otherwise :) Let me know what you think...

**Comment by linusg** [comment]
Yes, good point. Happy to use 0.01 as the default, but this could easily be customizable via a new constructor parameter - PR welcome, otherwise I can look into this on the weekend.

**Comment by Weeesel** [comment]
Closed by #21 .
