### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by Fam-of3** [linusg/xbox360controller#23]
`"C:\Program Files (x86)\Thonny\python.exe" -m pip install --no-cache-dir --user xbox360controller --disable-pip-version-check
Collecting xbox360controller
  Downloading xbox360controller-1.1.2.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Thonny\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jlw\\AppData\\Local\\Temp\\pip-install-fege9kqd\\xbox360controller\\setup.py'"'"'; __file__='"'"'C:\\Users\\jlw\\AppData\\Local\\Temp\\pip-install-fege9kqd\\xbox360controller\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jlw\AppData\Local\Temp\pip-pip-egg-info-83wdxem5'
         cwd: C:\Users\jlw\AppData\Local\Temp\pip-install-fege9kqd\xbox360controller\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jlw\AppData\Local\Temp\pip-install-fege9kqd\xbox360controller\setup.py", line 2, in <module>
        from xbox360controller import __version__
      File "C:\Users\jlw\AppData\Local\Temp\pip-install-fege9kqd\xbox360controller\xbox360controller\__init__.py", line 1, in <module>
        from xbox360controller.controller import Xbox360Controller
      File "C:\Users\jlw\AppData\Local\Temp\pip-install-fege9kqd\xbox360controller\xbox360controller\controller.py", line 15, in <module>
        from fcntl import ioctl
    ModuleNotFoundError: No module named 'fcntl'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: process returned with code 1

`

**Comment by linusg** [comment]
This is for Linux only.
