### ISSUE TITLE
Xbox One controller does not support rumbling 

### ISSUE THREAD

**Issue by oa01** [linusg/xbox360controller#25]
When i try to run the snippet of the Readme.md for rumbling:
```
import time
from xbox360controller import Xbox360Controller

with Xbox360Controller() as controller:
    controller.set_rumble(0.5, 0.5, 1000)
    time.sleep(1)
```  
I get a notice that my controller does not support rumbling.
Can you please add support for the xbox one controller?

**Comment by linusg** [comment]
>  Can you please add support for the xbox one controller?

I don't have one I could use for testing. Pull requests welcome though.
